package com.bogueratcreations.eaftoolkit.imgGallery.provider;

public class Images {

    public final static String[] imageUrls = new String[] {
            "http://boguerat.com/eafToolkit/eafToolkit(16).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(19).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(22).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(23).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(24).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(25).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(27).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(28).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(29).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(30).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(37).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(38).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(41).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(42).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(44).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(100).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(101).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(102).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(106).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(107).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(108).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(109).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(120).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(223).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(224).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(228).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(229).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(230).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(300).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(310).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(320).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(330).jpg",
            "http://boguerat.com/eafToolkit/eafToolkit(350).jpg",
    };

    /**
     * This are PicasaWeb thumbnail URLs and could potentially change. Ideally the PicasaWeb API
     * should be used to fetch the URLs.
     */
    public final static String[] imageThumbUrls = new String[] {
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(16).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(19).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(22).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(23).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(24).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(25).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(27).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(28).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(29).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(30).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(37).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(38).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(41).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(42).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(44).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(100).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(101).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(102).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(106).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(107).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(108).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(109).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(120).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(223).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(224).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(228).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(229).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(230).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(300).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(310).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(320).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(330).jpg",
            "http://boguerat.com/eafToolkit/Thumbs/eafToolkit(350).jpg",
    };
}
